<form class="form-horizontal">

    <div class="row">
        <div class="col-xs-2 col-xs-offset-10 text-center">
            <span class="glyphicon glyphicon-sort">
        </div>
    </div>

    <div class="filterslider form-group">
        <label for="maxprice" class="col-xs-3 control-label">Preis</label>
        <div class="col-xs-7">
            <input type="text" name="maxprice" id="maxprice"/>
        </div>
        <div class="radio col-xs-2 text-center">
            <label>
                <input type="radio" name="orderBy" id="orderByMaxprice" value="orderByMaxprice" checked>
            </label>
        </div>
    </div>

    <div class="filterslider form-group">
        <label for="maxtime" class="col-xs-3 control-label">Dauer</label>
        <div class="col-xs-7">
            <input type="text" name="maxtime" id="maxtime"/>
        </div>
        <div class="radio col-xs-2 text-center">
            <label>
                <input type="radio" name="orderBy" id="orderByMaxtime" value="orderByMaxtime">
            </label>
        </div>
    </div>

    <div class="filterslider form-group">
        <label for="maxway" class="col-xs-3 control-label">Entfernung</label>
        <div class="col-xs-7">
            <input type="text" name="maxway" id="maxway"/>
        </div>
        <div class="radio col-xs-2 text-center">
            <label>
                <input type="radio" name="orderBy" id="orderByMaxway" value="orderByMaxway">
            </label>
        </div>
    </div>

</form>