<div id="listEntry" class="entry panel panel-primary">
    <div class="panel-heading">
        <h2 class="name"></h2>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <h3>
                    <span class="tags"></span><br/>
                    <small class="type"></small>
                </h3>

                <button class="btn btn-success mapToggler pull-right"><span class="glyphicon glyphicon-map-marker"></span> Auf Karte zeigen</button>

                <p>
                    <span class="glyphicon glyphicon-map-marker"></span> <span
                        class="address"></span><br/>
                    <span class="glyphicon glyphicon-transfer"></span> <span
                        class="distance"></span>m
                </p>

                <div class="input-group">
                    <div class="input-group-btn">
                        <a class="url btn btn-info" target="_blank">
                            <span class="glyphicon glyphicon-link"></span> Website
                        </a>
                    </div>
                    <div class="form-control">
                        <span class="glyphicon glyphicon-earphone"></span>
                        <span class="telephone"></span>
                    </div>
                </div>

            </div>
            <div class="col-md-6">
                <div class="timecontainer">
                    <span class="glyphicon glyphicon-time bigglyph"></span>
                    <p>
                        <span class="deflabel">Laufzeit:</span> <span
                            class="waytime"></span>min<br/>
                        <span class="deflabel">Aufenthaltszeit:</span> <span
                            class="staytime"></span>min<br/>
                        <strong>
                            <span class="deflabel">Gesamtzeit:</span> <span class="time"></span>min
                        </strong>
                    </p>
                    <p>
                        <strong>
                            <span class="deflabel">Durchschnittskosten:</span>
                            <span class="avgcosts"></span>€
                        </strong>
                    </p>
                </div>

            </div>
        </div>
    </div>
    <div class="collapsible collapse">
        <iframe
            class="mapslink"
            frameborder="0" style="border:0"
            allowfullscreen>
        </iframe>
    </div>
</div>